services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:5050:80"  # Maps port 80 inside the container to port 5050 on the host
    environment:
      PGADMIN_DEFAULT_EMAIL: "your_email@example.com"  # Default administrator email
      PGADMIN_DEFAULT_PASSWORD: "your_password"  # Default administrator password
      PGADMIN_CONFIG_SERVER_MODE: "False" # Set to False to run in a single container
    volumes:
      - pgadmin-data:/var/lib/pgadmin  # Stores pgAdmin data in a volume
    networks:
      - postgres-network # Connect pgAdmin to the postgres network

  postgres:  # Optional:  Include this if you don't already have a PostgreSQL container running
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgadmin-data:
  postgres-data:  # Required if you're also running the PostgreSQL container

networks:
  postgres-network:  # Allows pgAdmin and PostgreSQL containers to communicate