services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src/:/app/src/
    environment:
      POSTGRES_URL: db:5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - shared-network
      - app-network
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

  shared-network:
    external: true

volumes:
  pg_data: