services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: yourusername
      POSTGRES_DB: yourdb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  py2db:
    build: ./python
    container_name: py2db
    environment:
      DB_HOST: postgres-db
      DB_NAME: yourdb
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
    depends_on:
      - postgres
    networks:
      - db-network
    volumes:
      - ./python/src:/app

networks:
  db-network:
    driver: bridge

