services:
  postgraphile:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://your_user:your_password@db:5432/your_database
      NODE_ENV: production
    volumes:
      - ./:/app/
    command: sh -c "ash"
    stdin_open: true
    tty: true

  postgres:  
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  pgadmin-data:
  postgres-data:  # Required if you're also running the PostgreSQL container

networks:
  postgres-network:  # Allows pgAdmin and PostgreSQL containers to communicate